name: "clients/go"

on:
  workflow_call:
    secrets:
      TIGERBEETLE_GO_DEPLOY_KEY:
        required: true

jobs:

  docs:
    # We use self hosted runners for M1 here. See macos.yml for an explaination
    permissions:
      contents: read

    strategy:
      matrix:
        os: [windows-latest] #, ubuntu-latest, macos-latest, [self-hosted, ARM64, macos-12.6], [self-hosted, ARM64, macos-13.2]]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # Grab Zig
      - run: ./scripts/install.${{ matrix.os == 'windows-latest' && 'bat' || 'sh' }}

      - if: matrix.os != 'windows-latest'
        run: |
          # Specifically for self-hosted M1 runners, OK if this fails on other envs.
          rm -rf /Users/macos/Library/Caches/go-build

          ./scripts/build.sh client_docs -- --language go

      # Set CC='zig.exe cc' for Windows.
      - if: matrix.os == 'windows-latest'
        run: |
          $env:CC = "$(pwd)\zig\zig.exe cc"
          .\scripts\build.bat client_docs
          .\zig-out\bin\client_docs --language go
      
      - if: matrix.os == 'ubuntu-latest'
        run: ./scripts/fail_on_diff.sh

