name: CI Pipeline

on:
  push:
    branches:
      - 'main'

  # Run on Merge queue
  merge_group:

  # Run CI for any PRs that target 'main' when they are opened or updated.
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize

jobs:
  client-go:
    uses: ./.github/workflows/clients-go.yml
    secrets:
      TIGERBEETLE_GO_DEPLOY_KEY: ${{ secrets.TIGERBEETLE_GO_DEPLOY_KEY }}
